# swagger配置
swagger:
  enabled: true
  api-info:
    appName: 'dhgh-door-api'
    title: 'dhgh-door-api'
    description: '门户网站接口服务'
    license: ''
    license-url: ''
    version: 'v1.0'
    contact-name: 'dhgh-door'
    #    contact-url: 'https://coding.net/u/zhuchuangang/p/thor/git'
    contact-email: ''
    #    terms-of-service-url: 'https://coding.net/u/zhuchuangang/p/thor/git'
    base-package: com.dhgh.dhghdoor.web
    oauth:
      clientId: test
      clientSecret: test
      access-token-uri: http://127.0.0.1:7777/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:7777/uaa/oauth/authorize